#base "scheme/clientscheme_settings.res"
#base "scheme/clientscheme_borders.res"
#base "../customizations/colors.res"
#base "scheme/clientscheme_fonts.res"
#base "scheme/clientscheme_icons.res"

#base "scheme/crosshair/scheme_blur.res"
#base "scheme/crosshair/scheme_dropshadow.res"
#base "scheme/crosshair/scheme_main.res"
#base "scheme/crosshair/scheme_outline.res"
