"Resource/UI/LoadoutPresetPanel.res"
{
	"loadout_preset_panel"
	{
		"ControlName"	"CLoadoutPresetPanel"
		"fieldName"		"loadout_preset_panel"

		"presetbutton_kv"
		{
			"zpos"			"20"
			"wide"			"25"
			"tall"			"25"
			"autoResize"	"0"
			"pinCorner"		"0"
			"visible"		"0"
			"enabled"		"1"
			"tabPosition"	"0"
			"font"			"HudFontMediumSmallBold"
			"textAlignment"	"center"
			"textinsetx"	"0"
			"dulltext"		"0"
			"brighttext"	"0"
			"Command"		""
			"sound_depressed"	"UI/buttonclick.wav"
			"sound_released"	"UI/buttonclickrelease.wav"
			"centerwrap"	"1"
			"paintborder"	"1"
			"paintbackground"	"1"
			"border"		"cutebutton"
			"border_override"	"cutebutton"
			"border_default"	"cutebutton"
			"border_armed"		"cutebutton_hover"
			"border_depressed"	"cutebutton_hover"
			"defaultBgColor_override"	"Normal"
			"depressedBgColor_override"	"Normal"
			"selectedBgColor_override"	"Normal_hover"
			"armedBgColor_override"	"Normal_hover"
		}
	}
}
